# Generated by Django 4.1.5 on 2023-09-09 11:52

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_eventpage_remove_galeriaartistas_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpage',
            name='informacion',
            field=wagtail.fields.StreamField([('rich_text', wagtail.blocks.StructBlock([('text', wagtail.blocks.RichTextBlock())]))], blank=True, use_json_field=None),
        ),
    ]
