# Generated by Django 4.1.5 on 2023-09-09 11:55

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_alter_eventpage_informacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventpage',
            name='informacion',
        ),
        migrations.AddField(
            model_name='eventpage',
            name='próximos_eventos',
            field=wagtail.fields.StreamField([('evento', wagtail.blocks.StructBlock([('text', wagtail.blocks.RichTextBlock())]))], blank=True, use_json_field=None),
        ),
    ]
