# Generated by Django 4.1.5 on 2023-09-09 11:56

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0004_remove_eventpage_informacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpage',
            name='próximos_eventos',
            field=wagtail.fields.StreamField([('rich_text', wagtail.blocks.StreamBlock([('richtext', wagtail.blocks.RichTextBlock()), ('event', wagtail.blocks.StructBlock([('event_name', wagtail.blocks.CharBlock(label='Nombre del evento', max_length=255, required=True)), ('event_content', wagtail.blocks.RichTextBlock(label='Contenido del evento', required=True))]))]))], blank=True, use_json_field=None),
        ),
    ]
