# Generated by Django 4.1.5 on 2023-09-09 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0005_alter_eventpage_próximos_eventos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventpage',
            name='próximos_eventos',
        ),
    ]
