# Generated by Django 4.1.5 on 2023-09-09 12:03

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0007_eventpage_próximos_eventos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpage',
            name='próximos_eventos',
            field=wagtail.fields.StreamField([('event', wagtail.blocks.StructBlock([('event_name', wagtail.blocks.CharBlock(label='Nombre del evento', max_length=255, required=True)), ('event_content', wagtail.blocks.RichTextBlock(label='Contenido del evento', required=True))]))], blank=True, use_json_field=None),
        ),
    ]
