# Generated by Django 4.1.5 on 2023-09-09 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0024_index_image_file_hash'),
        ('eventos', '0009_alter_eventpage_próximos_eventos'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpage',
            name='hero_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
