# Generated by Django 4.1.5 on 2023-01-27 11:29

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homepage_about_us_homepage_event_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='image',
            field=wagtail.fields.StreamField([('image', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('caption', wagtail.blocks.CharBlock(required=False))]))], blank=True, use_json_field=None),
        ),
    ]
