# Generated by Django 4.1.5 on 2023-01-27 12:10

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_homepage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='image',
            field=wagtail.fields.StreamField([('image', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('caption', wagtail.blocks.CharBlock(required=False))]))], blank=True, null=True, use_json_field=None),
        ),
    ]
