# Generated by Django 4.1.5 on 2023-02-02 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0024_index_image_file_hash'),
        ('home', '0011_blogpagegalleryimage_delete_homepagesponsorsimages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogPageGalleryImage',
            new_name='SponsorsGalleryImage',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='body',
        ),
    ]
