# Generated by Django 4.1.5 on 2023-09-08 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_homepage_hero_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='sponsors',
        ),
        migrations.DeleteModel(
            name='SponsorsGalleryImage',
        ),
    ]
