# Generated by Django 4.1.5 on 2023-02-10 12:14

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('miembros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galeriamiembros',
            name='descripcion',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
